export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>
        <p className="text-muted-foreground mb-4">Last updated: March 5, 2026</p>

        <div className="space-y-6 text-sm leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold mb-2">1. Acceptance of Terms</h2>
            <p>
              By accessing or using KAME (Kaizen AI Marketing Engine), you agree to be bound by these
              Terms of Service. If you do not agree, do not use the platform.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">2. Description of Service</h2>
            <p>
              KAME is an AI-powered marketing platform that generates video content and publishes it
              to connected social media accounts on behalf of authenticated users. The service
              includes content generation, scheduling, publishing, and analytics.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">3. User Accounts</h2>
            <p>
              You must provide accurate information when creating an account. You are responsible for
              maintaining the security of your account credentials and for all activities under your
              account.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">4. Social Media Connections</h2>
            <p>
              KAME connects to third-party social media platforms via OAuth. You authorize KAME to
              publish content on your behalf when you connect your accounts. You may disconnect at
              any time from the Connections dashboard.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">5. Credits &amp; Payments</h2>
            <p>
              Content generation consumes credits. Credits can be purchased using KairosCoin (KRC)
              on the Binance Smart Chain. All purchases are final. Credit balances do not expire.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">6. AI-Generated Content</h2>
            <p>
              Content is generated by AI and may not always be accurate or appropriate. You are
              responsible for reviewing content before it is published. KAME is not liable for any
              consequences of published content.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">7. Prohibited Use</h2>
            <p>
              You may not use KAME to generate or distribute content that is illegal, harmful,
              hateful, misleading, or violates third-party rights. Abuse may result in account
              termination.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">8. Limitation of Liability</h2>
            <p>
              KAME is provided &quot;as is&quot; without warranties. We are not liable for any
              indirect, incidental, or consequential damages arising from your use of the service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">9. Changes to Terms</h2>
            <p>
              We may update these terms at any time. Continued use of the service constitutes
              acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">10. Contact</h2>
            <p>
              For questions about these terms, contact us at support@kairos-777.com.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
